### ISSUE TITLE
`define`s Not Found When They're In Other Files

### ISSUE THREAD

**Issue by ProfMoo** [tim-koehler/Helm-Intellisense#46]
Hi! Very nice plugin!

One issue I'm running into is the plugin being able to find `define` blocks from other YAML files. For example, let's say I have two files:

1. A file called `_ports.yaml` where I `define` port constants that are used across the chart, like `{{- define "my.port" -}}`.
2. A file called `stateful-set.yaml`, which uses `{{ include "my.port" }}` to get the port value from `_ports.yaml`.

The practice is a bit unusual, but it works perfectly well in Helm and passes Helm linting checks. As such, I believe it should work this plugin.

Looking forward to further thoughts on this use-case.

**Comment by marcfrederick** [comment]
So if I understand correctly, you are defining [named templates](https://helm.sh/docs/chart_template_guide/named_templates/) containing your ports and including those around your chart. The problem seems to be, that named templates are defined in `.tpl` files by convention, so the code only scans those for `define` blocks (see [here](https://github.com/tim-koehler/Helm-Intellisense/blob/3667a51f5d530ec693cfabffa2aba1842430f6ea/src/utils.ts#L79-L95)).

The quick and simple fix for your case would be to rename your `_ports.yaml` to `_ports.tpl` if possible.

The extension is definitely making an incorrect assumption here though, which we should fix. @tim-koehler were there any reasons for limiting the scanning of `define` blocks to `.tpl` files?

**Comment by ProfMoo** [comment]
@marcfrederick Thanks for the info. I tried changing the file from `_ports.yaml` to `_ports.tpl` and the plugin worked as expected :).

So yes, I agree that the extension is making an incorrect assumption, but also that the workaround is totally permissible. Happy to either keep open or close the issue.

**Comment by tim-koehler** [comment]
@ProfMoo 
Just merged and released a new patch which also allows templates to also be found in non `.tpl` files (like `.yaml`). This should finally resolve your issue 😊 

@marcfrederick Thanks for your PR
